@startuml
object "飲み会" as 飲み会
飲み会 : 飲み会名
飲み会 : 開催日時
飲み会 : 参加者リスト
飲み会 : 請求金額

object "飲み会名" as 飲み会名
飲み会名 : value = "2020年新年会"

object "開催日時" as 開催日時
開催日時 : value = "2020-01-01 12:00:00"


object "参加者一覧" as 参加者一覧
参加者一覧 : membersList = List<参加者>

object "Aさん: 参加者" as 参加者A
参加者A : 氏名
参加者A : 幹事区分
参加者A : 支払区分

object "氏名" as 氏名A
氏名A : 氏名 = "Aさん"

object "幹事区分" as 幹事区分A
幹事区分A : 幹事区分 = "幹事"

object "支払区分" as 支払区分A
支払区分A : 支払区分 = "多め"

参加者一覧 -- 参加者A
参加者A -- 氏名A
参加者A -- 幹事区分A
参加者A -- 支払区分A

object "Bさん: 参加者" as 参加者B
参加者B : 氏名
参加者B : 幹事区分
参加者B : 支払区分

object "氏名" as 氏名B
氏名B : 氏名 = "Bさん"

object "幹事区分" as 幹事区分B
幹事区分B : 幹事区分 = "幹事以外"

object "支払区分" as 支払区分B
支払区分B : 支払区分 = "普通"

参加者一覧 -- 参加者B
参加者B -- 氏名B
参加者B -- 幹事区分B
参加者B -- 支払区分B

object "Cさん: 参加者" as 参加者C
参加者C : 氏名
参加者C : 幹事区分
参加者C : 支払区分

object "氏名" as 氏名C
氏名C : 氏名 = "Cさん"

object "幹事区分" as 幹事区分C
幹事区分C : 幹事区分 = "幹事以外"

object "支払区分" as 支払区分C
支払区分C : 支払区分 = "普通"

参加者一覧 -- 参加者C
参加者C -- 氏名C
参加者C -- 幹事区分C
参加者C -- 支払区分C

object "請求金額" as 請求金額
請求金額 : value = 10000

object "参加者ごとの支払金額" as 参加者ごとの支払金額

飲み会 -- 飲み会名
飲み会 -- 開催日時
飲み会 -- 参加者一覧
飲み会 -- 請求金額

@enduml