@startuml

package drinking_party {
    class 飲み会 {
        + 参加者ごとの支払金額一覧 割り勘()
    }
    class 飲み会名 {
    }
    class 開催日時 {
    }

    飲み会 --> 飲み会名
    飲み会 --> 開催日時
}

package member {
    class 参加者一覧 {
        - List<参加者>
        + 合計割合 合計割合を算出する()
    }
    class 参加者名 {
    }
    enum 幹事区分 {
        幹事
        幹事以外
    }
    enum 支払区分 {
        HIGH
        NORMAL
        LOW
    }

    参加者一覧 "1" --> "n" 参加者
    参加者 --> 参加者名
    参加者 --> 幹事区分
    参加者 --> 支払区分
}

package rate {
    class 合計割合 {
    }
}

package amount {
    class 請求金額 {
    }
    class 一つ分の支払金額 {
        + 一つ分の支払金額 算出する(請求金額, 合計割合)
    }
    class 一人当たりの支払金額 {
        + 一人当たりの支払金額 算出する(一つ分の支払金額, 支払区分)
    }
    class 参加者ごとの支払金額 {
    }
    class 参加者ごとの支払金額一覧 {
        + 合計支払金額  計算する()
    }
    class 合計支払金額 {
    }
    class 差額 {
        + 差額 算出する(請求金額, 合計支払金額)
    }

    一つ分の支払金額 --> 請求金額
    参加者ごとの支払金額 --> 一人当たりの支払金額
    参加者ごとの支払金額一覧 "1" --> "n" 参加者ごとの支払金額
    参加者ごとの支払金額一覧 --> 合計支払金額
    差額 --> 請求金額
    差額 --> 合計支払金額
}

飲み会 --> 請求金額
飲み会 ----> 参加者ごとの支払金額一覧
飲み会 --> 参加者一覧

一つ分の支払金額 --> 合計割合
参加者一覧 --> 合計割合

参加者ごとの支払金額一覧 --> 参加者一覧
参加者ごとの支払金額一覧 --> 請求金額
参加者ごとの支払金額一覧 --> 一つ分の支払金額
参加者ごとの支払金額一覧 --> 合計割合



一人当たりの支払金額 --> 一つ分の支払金額
一人当たりの支払金額 --> 支払区分

参加者ごとの支払金額 --> 参加者

@enduml