@startuml

package drinking_party {
    class 飲み会 {
        + 参加者ごとの支払金額一覧 割り勘()
    }

    飲み会 --> 飲み会名
    飲み会 --> 開催日時
}

package member {
    enum 幹事区分 {
        幹事
        幹事以外
    }
    enum 支払割合 {
        HIGH
        NORMAL
        LOW
    }

    参加者一覧 "1" --> "n" 参加者
    参加者 --> 参加者名
    参加者 --> 幹事区分
    参加者 --> 支払区分
    支払区分 --> 支払割合
}

package amount {
    class 一つ分の支払金額 {
        + 一つ分の支払金額 算出する(請求金額, 合計割合)
    }
    class 一人当たりの支払金額 {
        + 一人当たりの支払金額 算出する(一つ分の支払金額, 支払区分)
    }
    class 合計割合 {
        + 合計割合 算出する(参加者一覧)
    }
    class 参加者ごとの支払金額 {
    }

    一つ分の支払金額 --> 請求金額
    参加者ごとの支払金額 --> 一人当たりの支払金額
    参加者ごとの支払金額一覧 "1" --> "n" 参加者ごとの支払金額
}

飲み会 --> 参加者一覧
飲み会 --> 請求金額
飲み会 --> 参加者ごとの支払金額一覧

一つ分の支払金額 --> 合計割合
合計割合 --> 参加者一覧

一人当たりの支払金額 --> 一つ分の支払金額
一人当たりの支払金額 --> 支払区分

参加者ごとの支払金額 --> 参加者名

@enduml