@startuml
/'
## １番外のメソッド	
INパラ	参加者一覧、請求金額
OUTパラ	参加者ごとの支払金額
メソッド形式	参加者ごとの支払金額　f1(参加者一覧、請求金額)
	
## 参加者ごとの支払金額を算出するメソッド	
INパラ	参加者人数、請求金額
OUTパラ	参加者ごとの支払金額
メソッド形式	参加者ごとの支払金額　割り勘金額(参加者人数、請求金額)
	
## 参加者人数を算出するメソッド	
INパラ	参加者一覧
OUTパラ	参加者人数
メソッド形式	参加者人数　人数計算(参加者一覧)
	
## f1の実装	
参加者ごとの支払金額　f1(参加者一覧、請求金額) {	
   return 割り勘金額(人数計算(参加者一覧), 請求金額);	
}
'/

class 飲み会 {
    + 参加者ごとの支払金額　f1(参加者一覧、請求金額)
}

class 参加者ごとの支払金額 {
    + 参加者ごとの支払金額　割り勘金額(参加者人数、請求金額)
}

class 参加者一覧 {
    - List<参加者>
    + 参加者人数　人数計算(参加者一覧)
}

class 参加者 {
    - 支払区分
}

class 支払区分 {
    - 普通
}

class 参加者人数 {
    - int
}

class 請求金額 {
    - int
}

飲み会 -d-> 参加者ごとの支払金額
飲み会 -d-> 請求金額
飲み会 -d-> 参加者一覧
参加者ごとの支払金額 -d-> 参加者人数
参加者ごとの支払金額 -d-> 請求金額
参加者一覧 -d-> 参加者人数
参加者一覧 -d-> 参加者
参加者 -d-> 支払区分
@enduml
