@startuml
/'=================================='/
package 飲み会 {
  class 飲み会 {
    - 飲み会名
    - 開催日時
    - 参加者一覧
    - 請求金額
    + 登録結果 飲み会登録情報を登録する()
    + 参加者ごとの支払金額 割り勘する(請求金額, 参加者一覧)
  }
  class 飲み会名 {
    - String
  }

  class 開催日時 {
    - LocalDateTime
  }

  /'--------------------'/

  飲み会 -d-> 飲み会名
  飲み会 -d-> 開催日時
}

/'=================================='/
package 参加者 {
  enum 幹事区分 {
    幹事
    幹事以外
  }

  class 氏名 {
    - String
  }

  class 参加者 {
    - 氏名
    - 幹事区分
    - 支払区分
  }

  class 参加者一覧 {
    - List<参加者>
    + 参加者一覧 参加者を追加する(参加者)
    + 参加者一覧 参加者を削除する(参加者)
  }

  /'--------------------'/
  参加者一覧 "1" -> "n" 参加者
  参加者 -d-> 氏名
  参加者 -d-> 幹事区分
}

/'=================================='/
package 金額 #ffb6c1 {

  class 参加者ごとの支払金額 {
  }

  enum 支払区分 {
    多め
    普通
    少なめ
  }

  class 支払割合 {
  }

  class 請求金額 {
  }

  /'--------------------'/
}

/'=================================='/
飲み会 ---> 参加者一覧
参加者 --> 支払区分
参加者 --> 参加者ごとの支払金額 : caution
飲み会 --> "n" 参加者ごとの支払金額 : caution
飲み会 -> 請求金額

@enduml
